### ISSUE TITLE
EnderIO metals craft into FE2 exclusive nuggets that are incompatible with EnderIO nuggets

### ISSUE THREAD

**Issue by XanderHess** [wasliebob/FE2-1.7#11]
With FE2 installed, a Pulsating Iron Ingot (&lt;EnderIO:itemAlloy:5&gt;) crafts into 9 FE Pulsating Iron nuggets (&lt;ForestryExtras:item.fe.nugget.pulsating iron&gt;) instead of 9 EnderIO Pulsating Iron nuggets (&lt;EnderIO:itemMaterial:3&gt;).

Same with Vibrant Alloy, Energetic Alloy, Electrical Steel and Conductive Iron.

This prevents several EnderIO items from being craftable (Pulsating Crystal, Vibrant Crystal, Item Conduit)

This used to be fixable using MinecraftTweaker but with the 2.2 changes, the item names now have spaces in them, so MT can't resolve the names anymore.

**Comment by wasliebob** [comment]
Will look into it!

**Comment by XanderHess** [comment]
Easiest way to fix it is probably by putting the addShapelessRecipe() call in FEItemNugget.java:31 into a condition that's only true if there's not already an existing recipe.

**Comment by wasliebob** [comment]
I know how to fix it most likely, will fix it for next update :).

**Comment by wasliebob** [comment]
EnderIO doesn't add the nuggets to the Ore Dict, as i don't want to have EIO as a library i can't make this work. I'll ask CrazyPants to put the nuggets in the Ore Dictionary

**Comment by wasliebob** [comment]
Talked to CrazyPants, will be added soon. Next version will have the two EIO nuggets using Ore Dictionary. It will not work until EnderIO also did it's part (adding the nuggets ino the ore dictionary)
