### ISSUE TITLE
Crash with GenDustry for Forestry Unstable

### ISSUE THREAD

**Issue by davv1** [wasliebob/FE2-1.7#18]
https://github.com/bdew/gendustry/issues/122

**Comment by Manuepolis23** [comment]
please resolve this as soon as posible

**Comment by wasliebob** [comment]
Sorry i'm really busy at this moment with school, i will look at it as soon as i have time to do so.

**Comment by davv1** [comment]
What what about this bug? It is still  there?

**Comment by davv1** [comment]
Fixed
