### ISSUE TITLE
Crash With Forestry Extras 2-1.3 and 2-1.4

### ISSUE THREAD

**Issue by SJ1133** [wasliebob/FE2-1.7#9]
When used with forestry 3.0.0.90 The game crashes on startup and the same error is shown.

 Forestry Extras 2-1.3 : http://pastebin.com/Rf98HY14
 Forestry Extras 2-1.4 : http://pastebin.com/LrXtMzD0

**Comment by wasliebob** [comment]
Will look into it.

**Comment by wasliebob** [comment]
Fixed in latest build.
